export interface Lead {
  id: string;
  source_id: string | null;
  incident_type: string | null;
  incident_date: string | null;
  incident_location: string | null;
  incident_state: string | null;
  incident_city: string | null;
  incident_description: string | null;
  incident_location_county: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  contact_email: string | null;
  phone_normalized: string | null;
  address_zip: string | null;
  date_of_birth: string | null;
  language_preference: string | null;
  preferred_language: string | null;
  intake_language: string | null;
  contact_preference: string | null;
  preferred_contact_method: string | null;
  best_contact_time: string | null;
  best_time: string | null;
  availability: string | null;
  injuries: string[] | null;
  injury_description: string | null;
  injury_details: any[] | null;
  medical_care: string | null;
  treatment_started: string | null;
  treatment_er: boolean | null;
  treatment_urgent_care: boolean;
  treatment_imaging: boolean;
  treatment_pt: boolean;
  treatment_chiro: boolean;
  treatment_surgery: boolean;
  treatment_facilities: string[];
  treatment_types: string[];
  currently_treating: string | null;
  ongoing_treatment: boolean;
  treatment_duration_weeks: number | null;
  treatment_gap_days: number | null;
  ambulance_transport: boolean;
  hospitalized: boolean;
  hospitalized_nights: number | null;
  surgery_performed: string | null;
  surgery_recommended: boolean;
  permanent_injury_concern: boolean;
  collision_type: string | null;
  client_role: string | null;
  fault_indicator: string | null;
  other_vehicle_type: string | null;
  multi_vehicle_count: number | null;
  road_conditions: string | null;
  weather_conditions: string | null;
  vehicle_drivable: string | null;
  airbags_deployed: string | null;
  vehicle_year: string | null;
  vehicle_make: string | null;
  vehicle_model: string | null;
  vehicle_status: string | null;
  property_damage_estimate: string | null;
  work_impact: string | null;
  work_missed_days: number | null;
  lost_wages: boolean;
  lost_work: string | null;
  lost_work_duration: string | null;
  employment_status: string | null;
  employer_name: string | null;
  wage_info: string | null;
  medical_bills_range: string | null;
  medical_records_available: string | null;
  medical_bills_available: string | null;
  other_party_insured: string | null;
  other_party_insurance_company: string | null;
  client_has_health_insurance: string | null;
  client_has_um_uim: string | null;
  consumer_insurance_carrier: string | null;
  consumer_insurance_policy: string | null;
  at_fault_insurance_carrier: string | null;
  at_fault_insurance_policy: string | null;
  at_fault_party: string | null;
  has_police_report: boolean | null;
  police_called: string | null;
  citation_issued: string | null;
  citation_to_whom: string | null;
  has_photos: boolean | null;
  photo_count: number;
  has_witnesses: boolean;
  witness_count: number;
  urgency: string | null;
  consulted_other_attorneys: boolean | null;
  currently_represented: boolean;
  preexisting_conditions_disclosed: boolean;
  preexisting_conditions_notes: string | null;
  prior_claims_disclosed: boolean;
  initial_outreach_response: string | null;
  initial_outreach_response_time_hours: number | null;
  tcpa_consent: boolean;
  tcpa_consent_timestamp: string | null;
  hipaa_authorization: boolean;
  hipaa_authorization_timestamp: string | null;
  terms_accepted: boolean;
  terms_accepted_timestamp: string | null;
  privacy_policy_accepted: boolean;
  privacy_policy_version: string | null;
  voice_note_urls: string[];
  voice_note_transcriptions: string[];
  attachments: any[];
  narrative_sanitized: string | null;
  lead_score: string | null;
  lead_price: number | null;
  auto_score_details: Record<string, any>;
  fraud_flags: string[];
  metro_area: string | null;
  status: string | null;
  routing_status: string | null;
  source_tracking_code: string | null;
  is_active: boolean;
  is_available_for_offers: boolean;
  data_deletion_requested: boolean;
  data_deletion_requested_at: string | null;
  data_deleted_at: string | null;
  ops_notes_for_attorneys: string | null;
  outcome_status: string | null;
  decline_reason: string | null;
  closure_reason: string | null;
  created_at: string;
  updated_at: string;
  submitted_at: string | null;
  messages_processed: boolean;
  channel: string | null;
  who_is_at_fault: string | null;
  vehicle_damage: string | null;
  type_of_injury: string | null;
  type_of_vehicle_hit_the_client: string | null;
  type_of_document: string | null;
  voice_recording_url: string | null;
  documents_url: string | null;
  has_insurance_info: string | null;
  has_incident_report: string | null;
}
